### ISSUE TITLE
Segmentation fault when trying to download Shape Polygons more than once

### ISSUE THREAD

**Issue by Prindle19** [ngageoint/geoq#305]
When trying to download Shape Polygons(of feature layers), the first time it works fine, zip file is created, and downloads. 

Subsequent attempts to download the same shapefile causes the development server to crash:
Console shows
Error in `/geoq/pyenv/geoq/bin/python': free(): invalid pointer: 0x00007f41c803a4e0 ***

**Comment by stephenrjones** [comment]
Ugh, had hoped I had fixed that. The issue lies on 64-bit systems in how it accesses the gdal library. Not sure how we got a pointer hanging around when the shapefile is clicked again. May just need to ensure we initialize all elements before creating a shapefile

**Comment by jdaigneau** [comment]
I could not reproduce this bug on my machine. I was able to download as many shape polygons as I wanted to. I'm running CentOS 6.6 64bit. The only other difference between mine and Steve's is in the dependencies, since a few of mine are slightly newer.

I have:
gdal-0.1.9.2-7.rhel6.x86_64
armadillo-04.550.2-1
gdal-libs0:1.9.2-6.rhel6.x86_64
glibc-0:2.12-1.166.e16_7.1.1686

As opposed to Steve's:
gdal-0.1.9.2-6.rhel6.x86_64
armadillo-04.300.0-1
gdal-0.1.9.2-5.rhel6.x86_64
glibc-0:2.12-1.166.e16.1686

**Comment by stephenrjones** [comment]
Believe this issue has been resolved. Similar bug #357 still being worked.
