### ISSUE TITLE
Have a "rotated map" view

### ISSUE THREAD

**Issue by jaycrossler** [ngageoint/geoq#310]
Lots of imagery analysis is done when watching a helicopter or news feed video in one window, then drawing polygons or points onto the GeoQ map.  The mental process of translating oblique video footage that is constantly rotated into an overhead location is difficult.  It would be very useful to open a new window or tab that only shows map tiles (though overlay polygons would be great) and then rotate the map in this window).  If this second window then shows the footprint of that view in the primary GeoQ editor, that would help analysts properly place points/polygons.

**Comment by stephenrjones** [comment]
A new panel in the Tools area has been added for this. The 'Rotation Helper' will allow the user to rotate the current map view to allow for a different perspective. Points and polygons can be added with a rotated view, however since the coordinates have changed position the placement of feature types doesn't track with the mouse movement. If that becomes a requirement, we can look to provide an additional mouse event layer that will translate mouse movements to the rotated coordinates.
