### ISSUE TITLE
Use in Canada

### ISSUE THREAD

**Issue by neilmartis** [ngageoint/geoq#359]
Hi guys
I want to fork this application and use it Canada wide what file changes are necessary after doing so Any help?

**Comment by Bauerr** [comment]
Hi Neil, You are welcome to fork and stand up your own GeoQ with no restrictions. NGA has released this code with an MIT License.  If you run into some issues with standing up a server please post them to GitHub and we will respond as time permits.  Due to legal and policy issues NGA can not stand up and/or run software for groups or individuals outside the US Government or our mission set. 
Some good news is that we have some Chef Scripts and other links to stand up a GeoQ Server.

- GeoQ S2I Builder Image for OpenShift https://hub.docker.com/r/kevensen/centos-geoq-s2i/

- jason-callaway/geoq-postgresql

- ngageoint/geoq-chef-installer

FYI, Redhat has integrated GeoQ into OpenShift.  This means that for a small cost you can contact Redhat and they have the ability with OpenShift 3 (cloud) to stand up GeoQ servers in less than 2 minutes. This server can be linked to our GitHub Repository and then the server is updated whenever we push updates.
